[workspace]
members = [ "application", "node", "types", "utils"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
# Our crates
summit-types = {path = "types"}
summit-application= {path = "application"}
summit-utils = {path = "utils"}

anyhow = "1.0.98"
bytes = "1.10.1"

commonware-consensus = "0.0.57"
commonware-cryptography = "0.0.57"
commonware-storage = "0.0.57"
commonware-runtime ="0.0.57"
commonware-codec ="0.0.57"
commonware-p2p = "0.0.57"
commonware-broadcast = "0.0.57"
commonware-utils = "0.0.57"
commonware-resolver = "0.0.57"
commonware-macros = "0.0.57"


governor = "0.6.3"
rand = "0.8.5"
serde = {version = "1.0.219", features = ["derive"]}

futures = "0.3.31"
tokio = "1.46.0"
tracing = "0.1.41"

# todo: replace with seismic alloy where relevant
alloy-provider = { version = "1.0.9", features = ["hyper", "engine-api"] }
alloy-rpc-types-engine = { version = "1.0.9", features = ["serde", "ssz"] }
alloy-transport-http = { version = "1.0.9", features = ["hyper", "jwt-auth"] }
alloy-rpc-client = { version = "1.0.9", features = [
    "hyper",
    "alloy-transport-http",
] }
alloy-eips ={version =  "1.0.19", features = ["ssz"]}
alloy-primitives = "1.2.1"

http-body-util = "0.1.3"
tower = "0.5.2"
clap = {version = "4.5.40", features = ["derive"]}
