eth_genesis_hash = "0x655cc1ecc77fe1eab4b1e62a1f461b7fddc9b06109b5ab3e9dc68c144b30c773"
leader_timeout_ms = 2000
notarization_timeout_ms = 4000
nullify_timeout_ms = 4000
activity_timeout_views = 256
skip_timeout_views = 32
max_message_size_bytes = 104857600
namespace = "_SEISMIC_BFT"
identity = "85937067a60f02a8f7512a12fe7a07f7721369b9a3b170930cb44f7ae37bb6dd4f6d1fccf7e97ea947ab80bd41faff9bb909f763811465ef05e037647dfa823f6e32045d981e8720cf0e7c649f730dfe680dc121dbe407c5348435c0528425488b7ee04aef7b76e8c69359c57c9653b754126d8be5c86192780c823bf887a30c748b40544d6427755b52a9e4f02ee190"

[[validators]]
public_key = "1be3cb06d7cc347602421fb73838534e4b54934e28959de98906d120d0799ef2"
ip_address = "127.0.0.1:26600"

[[validators]]
public_key = "32efa16e3cd62292db529e8f4babd27724b13b397edcf2b1dbe48f416ce40f0d"
ip_address = "127.0.0.1:26610"

[[validators]]
public_key = "ce9b314ac9d55d28bedf543164120eecf737380015c977eaa78d59894bbccf52"
ip_address = "127.0.0.1:26620"

[[validators]]
public_key = "f205c8c88d5d1753843dd0fc9810390efd00d6f752dd555c0ad4000bfcac2226"
ip_address = "127.0.0.1:26630"
